name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo start
        run: echo "Starting deployment workflow"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Environment check:"
          env | grep -v -i key
          echo "Python version:"
          python3 --version

      - name: Check secrets
        run: |
          echo "Checking if secrets are set (not showing values):"
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "SSH_PRIVATE_KEY is set"
          else
            echo "SSH_PRIVATE_KEY is not set"
          fi
          if [ -n "${{ secrets.SERVER_USER }}" ]; then
            echo "SERVER_USER is set"
          else
            echo "SERVER_USER is not set"
          fi
          if [ -n "${{ secrets.SERVER_IP }}" ]; then
            echo "SERVER_IP is set"
          else
            echo "SERVER_IP is not set"
          fi