name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Match your Python version

      - name: Install dependencies for workflow
        run: |
          python -m pip install --upgrade pip
          pip install paramiko  # For SSH and SCP, if needed in the script

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Prepare SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Transfer the project files
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new -r * $SERVER_USER@$SERVER_IP:~/Alsat-API/

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=accept-new $SERVER_USER@$SERVER_IP << 'EOF'
            # Navigate to the project directory
            cd ~/Alsat-API

            # Activate virtual environment
            if [ ! -d "venv" ]; then
              python3 -m venv venv  # Create venv if not already created
            fi
            source venv/bin/activate

            # Upgrade pip and install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Run migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart the Gunicorn process via PM2
            pm2 stop alsat-backend || true
            pm2 delete alsat-backend || true
            pm2 start $(which gunicorn) --name alsat-backend --interpreter python3 -- config.wsgi:application --bind 0.0.0.0:8000

            # Monitor resources
            echo "Current memory usage:"
            free -h
            echo "Disk usage:"
            df -h
          EOF
